name: Build GeoJSON tile server container

on:
  push:
    branches: main
    paths:
      - 'server/**'
      - '.github/actions/server.yml'

jobs:
  build:
    env:
        IMAGE: ghcr.io/russss/osm-addresses-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
              ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}
